name: Elixir CI

on:
  push:
    # It's common to use 'main' now, but 'master' works just as well.
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    name: Build and Test on OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ['27.0', '28.0']
        elixir: ['1.18', '1.19']

    env:
      MIX_ENV: test

    steps:
      - name: Checkout Repository
        # Updated to the latest major version for security and features
        uses: actions/checkout@v4

      - name: Setup Elixir and OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          # This enables caching of deps and _build directories for faster runs
          cache-deps: true

      - name: Install Dependencies
        run: mix deps.get

      - name: Check Code Formatting
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors

      - name: Run Tests with Coverage and Post Feedback
        # This action runs the tests and posts coverage feedback to the PR
        uses: josecfreittas/elixir-coverage-feedback-action@v1
        with:
          # The GITHUB_TOKEN is required for the action to post comments
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Set a minimum coverage threshold
          coverage_threshold: 75
          # Explicitly define the test command for clarity
          test_command: mix test --cover
